version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/export-opportunities
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: localhost
          PGUSER: exops
          RAILS_ENV: test
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: user
          POSTGRES_DB:  export_opportunities_test
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    branches:
      only: XOT-597-circleci
    steps:
      - checkout # check out the code in the project directory
      # restore bundle cache  
      - restore_cache:
          keys:
            - exops-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # store bundle cache
      - save_cache:
          key: exops-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle

      - run: echo "hello world" # run the `echo` command
